### ISSUE TITLE
Question on using os.putenv

### ISSUE THREAD

**Issue by NikosAlexandris** [bossjones/scarlett_os#390]
Why use `os.environ` and then `os.putenv`

here: https://github.com/bossjones/scarlett_os/blob/571d360eb2d825bdceb79ab994cb83f07761121f/scarlett_os/internal/debugger.py#L38

and here: https://github.com/bossjones/scarlett_os/blob/571d360eb2d825bdceb79ab994cb83f07761121f/scarlett_os/internal/debugger.py#L39

In some script of mine, I need to modify some environment variable. Apparently, `putenv` does not work always. I don't understand why so.

Thanks for any hints.

ps- What does `#noqa` mean?

**Comment by bossjones** [comment]
Hi! So sorry I missed this message, I didn't see it at all!

The `os.environ` and `os.putenv` is a product of some old PyGobject documentation that specified you needed to call both in order for the Gst C bindings to actually work. It was a hack due to some problems in older versions of PyGObject. I think these days, things are much better. A quick github search to show some other repos doing the same thing: https://github.com/search?q=os.putenv%28%22GST_DEBUG_DUMP_DIR_DIR&type=Code

I probably isn't needed anymore at all, and it is very much a hack!

`# noqa` is used to tell my linter ( pylint at the time ) to ignore that line of code from static analysis. 

You probably already figured out all of this, but I wanted to make sure I responded!

**Comment by NikosAlexandris** [comment]
No, actually I did not dig further.
Thank you, useful to know.
